### ISSUE TITLE
Failed to activate the opened-files package

### ISSUE THREAD

**Issue by aujkis** [paulpflug/opened-files#13] opened 2015-06-29 09:05 UTC
[Enter steps to reproduce below:]
1. Updated Atom to 1.0
2. Installed package
3. Received activation error

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [opened-files](https://github.com/paulpflug/opened-files) package, v0.2.1
### Stack Trace

Failed to activate the opened-files package

```
At string is not a function

TypeError: string is not a function
  at load (/Users/Austris/.atom/packages/opened-files/lib/main.coffee:49:19)
  at /Users/Austris/.atom/packages/opened-files/lib/main.coffee:57:11
  at Main.module.exports.Main.activate (/Users/Austris/.atom/packages/opened-files/lib/main.coffee:59:9)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -0:49.2.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:44.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "opened-files": {}
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
atomatigit, v1.5.3
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
autohide-tree-view, v0.20.2
bookmarks, v0.35.0
chary-tree-view, v0.2.3
color-picker, v2.0.7
editor-stats, v0.17.0
file-icons, v1.5.8
filesize, v0.2.0
flex-tool-bar, v0.4.2
git-projects, v1.14.1
git-tab-status, v1.9.2
gutter-shadow, v0.5.0
highlight-selected, v0.10.1
keyboard-scroll, v0.4.0
keyboard-sounds, v0.2.0
language-dotenv, v1.0.0
language-fish-shell, v1.0.2
language-generic-config, v0.2.0
language-gitignore, v0.2.0
language-hosts, v0.1.2
language-slim, v0.4.0
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
minimap-selection, v4.2.0
open-recent, v2.2.4
opened-files, v0.2.1
pigments, v0.8.1
read-only-indicator, v0.2.0
save-session, v0.15.6
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-git-status, v0.1.1
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by paulpflug** [comment] 2015-06-29 10:11
should be fixed.
Thanks for reporting :smile:

**Comment by aujkis** [comment] 2015-06-30 06:25
Getting the same error w/ `0.2.3` :(

**Comment by paulpflug** [comment] 2015-06-30 06:29
Then I will dig deeper 😀

I suspect the tree view auto hide package as problematic. I will test it 
later..

Am 30. Juni 2015 08:25:14 schrieb Austris Landmanis notifications@github.com:

**Comment by paulpflug** [comment] 2015-07-01 22:24
no .. wasn't that package. Could you please try to reinstall opened-files? Are you working in dev mode?

I have no clue how this error can occur.

I tested updating atom in a virtual machine and got some wired behavior, but a reload of atom fixed everything..

**Comment by ryanzec** [comment] 2015-07-30 10:28
I have tried this plugin (because the styling of the other one is messed up) however this does not seem to work.  I don't get any error but I don't see this either, not sure what is happening.

**Comment by paulpflug** [comment] 2015-07-31 08:01
it will be hidden when no files are opened. I need more information to make it reproducible, for me it works..

**Comment by isGabe** [comment] 2015-12-18 17:46
I just installed this package for the first time and got a similar issue, but a different type of error. Tried restarting Atom, enabling/disabling the package, uninstalling/reinstalling the package, etc.

Steps to reproduce:
1. Install package
2. Enable package

Atom Version: 1.2.4
System: Mac OS X 10.10.5
Thrown From: opened-files package, v0.2.8

Failed to activate the opened-files package

Stack trace:

```
Error: ENOENT: no such file or directory, open '/Users/gabe/.atom/projects.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports.readFileSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:158:21)
    at ProjectManager.module.exports.ProjectManager.getProject (/Users/gabe/.atom/packages/opened-files/lib/project-manager.coffee:18:23)
    at ProjectManager.getProject (/Users/gabe/.atom/packages/opened-files/lib/project-manager.coffee:1:1)
    at ProjectManager.module.exports.ProjectManager.getProjectSetting (/Users/gabe/.atom/packages/opened-files/lib/project-manager.coffee:35:16)
    at ProjectManager.getProjectSetting (/Users/gabe/.atom/packages/opened-files/lib/project-manager.coffee:1:1)
    at Vue.module.exports.beforeCompile (/Users/gabe/.atom/packages/opened-files/components_compiled/app.js:232:31)
    at Vue.exports._callHook (/Users/gabe/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/instance/events.js:134:19)
    at Vue.exports._initElement (/Users/gabe/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/instance/compile.js:91:8)
    at Vue.exports._compile (/Users/gabe/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/instance/compile.js:33:10)
    at Vue.exports.$mount (/Users/gabe/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/api/lifecycle.js:29:8)
    at new OpenedFiles (/Users/gabe/.atom/packages/opened-files/lib/opened-files.coffee:41:18)
    at load (/Users/gabe/.atom/packages/opened-files/lib/main.coffee:62:32)
    at /Users/gabe/.atom/packages/opened-files/lib/main.coffee:77:11
    at Main.module.exports.Main.activate (/Users/gabe/.atom/packages/opened-files/lib/main.coffee:80:9)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:333:19
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:624:20
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:809:29)
    at Config.module.exports.Config.setRawValue (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:601:19)
    at Config.module.exports.Config.set (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:379:12)
    at Package.module.exports.Package.enable (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

```
➜  .atom  apm list
Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.23.0
├── autocomplete-snippets@1.8.0
├── autoflow@0.26.0
├── autosave@0.23.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.0.0
├── base16-tomorrow-light-theme@1.0.0
├── bookmarks@0.38.0
├── bracket-matcher@0.79.0
├── command-palette@0.37.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.194.0
├── fuzzy-finder@0.93.0
├── git-diff@0.57.0
├── go-to-line@0.30.0
├── grammar-selector@0.48.0
├── image-view@0.56.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.49.0
├── language-clojure@0.18.0
├── language-coffee-script@0.45.0
├── language-csharp@0.11.0
├── language-css@0.35.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.40.0
├── language-html@0.42.0
├── language-hyperlink@0.15.0
├── language-java@0.16.1
├── language-javascript@0.100.0
├── language-json@0.17.1
├── language-less@0.28.3
├── language-make@0.20.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.0
├── language-perl@0.31.0
├── language-php@0.34.0
├── language-property-list@0.8.0
├── language-python@0.41.0
├── language-ruby@0.62.0
├── language-ruby-on-rails@0.24.0
├── language-sass@0.43.0
├── language-shellscript@0.20.0
├── language-source@0.9.0
├── language-sql@0.19.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.34.0
├── language-yaml@0.24.0
├── line-ending-selector@0.3.0
├── link@0.31.0
├── markdown-preview@0.156.1
├── metrics@0.53.0
├── notifications@0.62.1
├── one-dark-syntax@1.1.1
├── one-dark-ui@1.1.5
├── one-light-syntax@1.1.1
├── one-light-ui@1.1.5
├── open-on-github@0.40.0
├── package-generator@0.41.0
├── release-notes@0.53.0
├── settings-view@0.232.0
├── snippets@1.0.1
├── solarized-dark-syntax@0.39.0
├── solarized-light-syntax@0.23.0
├── spell-check@0.63.0
├── status-bar@0.80.0
├── styleguide@0.45.0
├── symbols-view@0.110.1
├── tabs@0.88.0
├── timecop@0.33.0
├── tree-view@0.198.0
├── update-package-dependencies@0.10.0
├── welcome@0.32.0
├── whitespace@0.32.0
└── wrap-guide@0.38.1
```

```
/Users/gabe/.atom/packages (4)
├── emmet@2.3.17
├── opened-files@0.2.8
├── tree-view-open-files@0.3.0
└── twilight-syntax@0.7.0
```

config:

```
"*":
  "exception-reporting":
    userId: "c95d19e5-f5cc-6cc7-6b21-2c1b7313b04c"
  welcome:
    showOnStartup: false
  editor:
    fontSize: 13
    invisibles: {}
    fontFamily: "Menlo"
    tabLength: 4
    tabType: "hard"
  core:
    themes: [
      "atom-dark-ui"
      "twilight-syntax"
    ]
    disabledPackages: [
      "tree-view-open-files"
    ]
  "tree-view-open-files": {}
  "opened-files": {}
```

**Comment by isGabe** [comment] 2015-12-18 17:49
FWIW, I manually created a blank projects.cson file in my ~/.atom and it seemed to fix the issue. Maybe a check for the existence of that file is needed?

**Comment by rugk** [comment] 2015-12-28 14:33
This also happens when I activate/deactivate some packages with [package-cop](https://atom.io/packages/package-cop).

**Comment by Venryx** [comment] 2016-03-31 01:04
I got the same error as FStop above. (though with a newer version of Atom--1.6.1)
= = = = = = = = = =
Steps to reproduce:

1) Install package
2) Enable package

**Atom Version**: 1.6.1
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [opened-files](https://github.com/paulpflug/opened-files) package, v0.2.8

### Stack Trace

Failed to activate the opened-files package

```
At ENOENT: no such file or directory, open 'C:\Users\Stephen\.atom\projects.cson'

Error: ENOENT: no such file or directory, open 'C:\Users\Stephen\.atom\projects.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports.readFileSync (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\node_modules\season\lib\cson.js:158:21)
    at ProjectManager.module.exports.ProjectManager.getProject (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/project-manager.coffee:18:23)
    at ProjectManager.getProject (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/project-manager.coffee:1:1)
    at ProjectManager.module.exports.ProjectManager.getProjectSetting (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/project-manager.coffee:35:16)
    at ProjectManager.getProjectSetting (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/project-manager.coffee:1:1)
    at Vue.module.exports.beforeCompile (C:\Users\Stephen\.atom\packages\opened-files\components_compiled\app.js:232:31)
    at Vue.exports._callHook (C:\Users\Stephen\.atom\packages\opened-files\node_modules\atom-vue-component-loader\node_modules\vue\src\instance\events.js:134:19)
    at Vue.exports._initElement (C:\Users\Stephen\.atom\packages\opened-files\node_modules\atom-vue-component-loader\node_modules\vue\src\instance\compile.js:91:8)
    at Vue.exports._compile (C:\Users\Stephen\.atom\packages\opened-files\node_modules\atom-vue-component-loader\node_modules\vue\src\instance\compile.js:33:10)
    at Vue.exports.$mount (C:\Users\Stephen\.atom\packages\opened-files\node_modules\atom-vue-component-loader\node_modules\vue\src\api\lifecycle.js:29:8)
    at new OpenedFiles (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/opened-files.coffee:41:18)
    at load (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/main.coffee:62:32)
    at file:///C:/Users/Stephen/.atom/packages/opened-files/lib/main.coffee:77:11
    at Main.module.exports.Main.activate (file:///C:/Users/Stephen/.atom/packages/opened-files/lib/main.coffee:80:9)
    at Package.module.exports.Package.activateNow (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:181:20)
    at C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:155:32
    at Package.module.exports.Package.measure (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:92:15)
    at C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:148:26
    at Package.module.exports.Package.activate (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Stephen\AppData\Local\atom\app-1.6.1\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -9:51.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:26.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -8:24.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  2x -8:24.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:24.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 23x -7:36.6.0 expose:toggle (atom-text-editor.editor.is-focused)
  2x -3:11 core:backspace (atom-text-editor#minimap.charHeight.editor.mini.is-focused)
  2x -2:08.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:29 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
expose, v0.11.1
highlight-selected, v0.11.2
minimap, v4.21.0
opened-files, v0.2.8
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Closed as completed** 2016-04-01 10:28 UTC
